### ISSUE TITLE
imanant-tool - loading own ant drawings

### ISSUE THREAD

**Issue by disposedtrolley** [AntTargett/Ant-CLI-Tool#1]
The most comprehensive collection of ASCII ants I've _ever_ seen.

Would be awesome I could save my own ant drawings into the tool, and have them randomly printed out to the terminal.

**Comment by AntTargett** [comment]
Like the idea, will see this implemented in the next version 👌

**Comment by AntTargett** [comment]
Can now be done in version 1.8.8 (lel) 
You can now upload your own askiiArt files to the askiiArt folder and then set them to the currentFile from the cli 👍
